# Travis CI Configuration file

# Language
language: python
python:
  - "2.7"

# Safelist
branches:
  only:
  - master
  - auto_test

# Custom configuration
sudo:
  - false

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

notifications:
  slack:
    on_success: always
