name: dragons
channels:
  - astroconda
dependencies:
  - python=3.5
  - astropy
  - pip
  - pip:
    - future
    - python-dateutil
    - coveralls
    - "--editable=git+git://github.com/GeminiDRSoftware/DRAGONS@master#egg=DRAGONS"
