name: dragonsenv
channels:
  - astroconda
dependencies:
  - astropy
  - configparser
  - dateutil
  - pip
  - pip:
    - coveralls
    - "--editable=git+git://github.com/GeminiDRSoftware/DRAGONS@master#egg=DRAGONS"
