name: dragons
channels:
  - astroconda
dependencies:
  - python=3.6
  - astropy
  - pip
  - pip:
    - future
    - coveralls
    - "--editable=git+git://github.com/GeminiDRSoftware/DRAGONS@master#egg=DRAGONS"
